"""
Exchange referral data.
Edit EXCHANGES list to update referral links or add new exchanges.
"""

EXCHANGES = [
    {
        "name": "Binance",
        "emoji": "⭐",
        "custom_emoji_id": "5343922009036330426",
        "url": "https://www.binance.com/register?ref=MUFND00U",
        "bonus": "До $600 USDT бонус новым пользователям",
        "label": "⭐ Binance — Зарегистрироваться",
        "desc": "Крупнейшая биржа в мире",
    },
    {
        "name": "Bybit",
        "emoji": "🔶",
        "custom_emoji_id": "5341456302671436527",
        "url": "https://www.bybit.com/invite?ref=KYOKBM",
        "bonus": "До $30,000 бонус при регистрации",
        "label": "🔶 Bybit — Зарегистрироваться",
        "desc": "Топ-2 по объёму фьючерсов",
    },
    {
        "name": "OKX",
        "emoji": "⬛",
        "custom_emoji_id": "5343952653627987380",
        "url": "https://okx.com/join/28151057",
        "bonus": "До $10,000 бонус + Mystery Box",
        "label": "⬛ OKX — Зарегистрироваться",
        "desc": "3-я по объёму торговли",
    },
    {
        "name": "Bitget",
        "emoji": "💎",
        "custom_emoji_id": "5341639246803408829",
        "url": "https://share.bitget.com/u/7PT1VLE2",
        "bonus": "До $6,200 бонус новым трейдерам",
        "label": "💎 Bitget — Зарегистрироваться",
        "desc": "Лучшие условия для копитрейдинга",
    },
    {
        "name": "BingX",
        "emoji": "🌐",
        "custom_emoji_id": "5341570759254910472",
        "url": "https://bingxdao.com/invite/PLW3Y3/",
        "bonus": "До $5,000 бонус при регистрации",
        "label": "🌐 BingX — Зарегистрироваться",
        "desc": "Копитрейдинг и социальная торговля",
    },
    {
        "name": "KuCoin",
        "emoji": "🦁",
        "custom_emoji_id": "5341316475716148607",
        "url": "https://www.kucoin.com/r/rf/QBSA928D",
        "bonus": "До $500 бонус для новых пользователей",
        "label": "🦁 KuCoin — Зарегистрироваться",
        "desc": "Более 700 торговых пар",
    },
    {
        "name": "MEXC",
        "emoji": "🚀",
        "custom_emoji_id": "5341294811901104112",
        "url": "https://promote.mexc.com/r/dMYee62f0r",
        "bonus": "До $8,000 бонус при регистрации",
        "label": "🚀 MEXC — Зарегистрироваться",
        "desc": "Листинг новых монет #1",
    },
    {
        "name": "Weex",
        "emoji": "⚡",
        "custom_emoji_id": "5341384155810800683",
        "url": "https://weex.com/register?vipCode=2s4sb",
        "bonus": "Бонус по промокоду 2s4sb",
        "label": "⚡ Weex — Зарегистрироваться",
        "desc": "Быстрорастущая биржа деривативов",
    },
    {
        "name": "Gate.io",
        "emoji": "🚪",
        "custom_emoji_id": "5341469045839403545",
        "url": "https://www.gate.com/ru/referral/earn-together/invite/BQcWUw0K?ref=BQcWUw0K&ref_type=103",
        "bonus": "До $10,000 бонус новым пользователям",
        "label": "🚪 Gate.io — Зарегистрироваться",
        "desc": "Топ-5 по объёму, 1700+ монет",
    },
]
